name: Deploy to IONOS

on:
  push:
    paths:
      - '**' # includes
      - '!README.md' # excludes

jobs:
  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    env:
      DN_SERVICE_HOST: 'api-eu.ionos.space'
      DN_PROJECT_ID: '99dd94df-fa02-402b-b5a8-5c19327e0628'
      RUN_CI: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    outputs:
      run_ci: ${{ steps.result.outputs.run_ci }}
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          service-host: ${{ env.DN_SERVICE_HOST }}
          project: ${{ env.DN_PROJECT_ID }}
          api-key: ${{ secrets.IONOS_API_KEY }}
      - name: Log
        run: |
          echo "::group::Results"
          echo "Outputs ${{ steps.project.outputs }}"
          echo "Auto deployment ${{ env.RUN_CI == 'true' && 'enabled' || 'skipped' }}"
          echo "::endgroup::"
      - name: Result
        id: result
        run: echo "::set-output name=run_ci::${{ env.RUN_CI == 'true' }}"
  