name: Deploy to IONOS

on:
  push:
    paths:
      - "**" # includes
      - "!README.md" # excludes

jobs:
  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    env:
      IONOS_SERVICE_HOST: "api-eu.ionos.space"
      IONOS_PROJECT_ID: "99dd94df-fa02-402b-b5a8-5c19327e0628"
      RUN_CI: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    outputs:
      run_ci: ${{ steps.result.outputs.run_ci }}
      project: ${{ steps.result.outputs.project }}
      test: ${{ steps.result.outputs.test }}
      foo: ${{ steps.result.outputs.foo }}
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          service-host: ${{ env.IONOS_SERVICE_HOST }}
          project: ${{ env.IONOS_PROJECT_ID }}
          api-key: ${{ secrets.IONOS_API_KEY }}
      - name: Log
        run: |
          echo "::group::Results"
          echo "Project ${{ toJSON(steps.project.outputs) }}"
          echo "Auto deployment ${{ env.RUN_CI == 'true' && 'enabled' || 'skipped' }}"
          echo "::endgroup::"
      - name: Result
        id: result
        run: |
          echo "::set-output name=run_ci::${{ env.RUN_CI == 'true' }}"
          echo "::set-output name=project::foo"
          echo "::set-output name=test::${{ steps.project.outputs.site-url }}"
          echo "::set-output name=foo::{ "name": "foo", "payload": "123" }"
  build_and_deploy:
    name: Build & Deploy
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          echo ${{ needs.preflight.outputs.run_ci }}
          echo ${{ needs.preflight.outputs.project }}
          echo ${{ needs.preflight.outputs.test }}
          echo ${{ needs.preflight.outputs.foo }}
          echo ${{ fromJSON(needs.preflight.outputs.foo).name }}
