name: Publish website

on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Deploy FTP
      uses: sebastianpopp/ftp-action@master
      with:
        host: "ftp.example.com"
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "public"
        remoteDir: "hunsalz/www"
