name: Deploy to GitHub Pages

on: [push]

jobs:
  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    env:
      GH_TOKEN_AVAILABLE: ${{ secrets.GH_TOKEN && true || false }}
      RUN_CI: ${{ !contains(github.event.head_commit.message, 'skip ci') && true || false }}
    outputs:
      run_build: ${{ steps.result.outputs.run_build }}
    steps: 
      - name: Log
        run: |
          echo "::group::Results"
          echo "GitHub token ${{ env.GH_TOKEN_AVAILABLE && 'available' || 'unavailable' }}"
          echo "Auto deployment ${{ env.RUN_CI && 'enabled' || 'skipped' }}"
          echo "::endgroup::"
      - name: Result
        id: result
        run: echo "::set-output name=run_build::${{ env.GH_TOKEN_AVAILABLE && env.RUN_CI }}"
  build:
    name: Build
    needs: preflight
    runs-on: ubuntu-latest
    env:
      RUN_BUILD: ${{ needs.preflight.outputs.run_build }}
      SITE_TITLE: My home is my castle
      SITE_URL: https://hunsalz.github.io
      PATH_PREFIX: /hunsalz.de
    steps:
      - name: Check preflight result
        run: echo ":warning Build stopped"
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Prepare env
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Build project
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: Deploy build to ${{ env.SITE_URL }}${{ env.PATH_PREFIX }}
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          build_dir: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Nothing yet"