name: Deploy to pages.github.com

on: [push]

env:
  GH_TOKEN_AVAILABLE: ${{ secrets.GH_TOKEN && true || false }}
  RUN_DEPLOYMENT: ${{ !contains(github.event.head_commit.message, 'skip deploy') && true || false }}
  SITE_TITLE: My home is my castle
  SITE_URL: https://hunsalz.github.io
  PATH_PREFIX: /hunsalz.de

jobs:
  preflight:
    - name: GitHub token is ${{ env.GH_TOKEN_AVAILABLE && 'available' || 'unavailable' }}
    - name: Auto deployment will be ${{ env.RUN_DEPLOYMENT && 'executed' || 'skipped' }}
  build:
    if: env.GH_TOKEN_AVAILABLE && env.RUN_DEPLOYMENT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Prepare env (node -v ${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build project
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: Deploy build to ${{ env.SITE_URL }} ${{ env.PATH_PREFIX }}
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          build_dir: dist