name: Deploy to pages.github.com

on: [push]

env:
  HAS_GH_TOKEN: ${{ secrets.GH_TOKEN }}
  SITE_URL: https://hunsalz.github.io
  PATH_PREFIX: /hunsalz.de

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Prepare env (node -v ${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build project
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: Deployment ${{ secrets.GH_TOKEN != '' && 'enabled' || 'disabled' }}
        if: env.HAS_GH_TOKEN != '' # run deployment not until GH_TOKEN is available
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          build_dir: dist/